### ISSUE TITLE
Auto update(r)?

### ISSUE THREAD

**Issue by ghost** [surfbirdapp/surfbird#22]
**This is just a creative idea at hand for feature posibility.**

GitHub provides JSONized information about the repositories and maybe even in branch form, could an occasional timer be executed to compare the hashes of the project files of which will compile a list of changed files in the master branch, then prompt the user for update?  
After calculating the hashes locally and comparing, in theory couldn't the latest files be downloaded by prefixing them with `https://raw.githubusercontent.com/surfbirdapp/surfbird/master/`?

My reason for considering this is to just simplify and reduce time of downloading the repository changes each time a stable update is applied in the future.

**Comment by pixeldesu** [comment]
I could build that with [Squirrel](https://github.com/Squirrel) later on, not in any kind of focus right now!
