### ISSUE TITLE
Profile Creation Dialogue

### ISSUE THREAD

**Issue by pixeldesu** [surfbirdapp/surfbird#55]
As we already have a column creation dialogue, we now also need a profile creation dialogue! There's not too much it needs, the only thing that gets passed to the constructor is the name the profile should get.

The [Column creation dialogue](https://github.com/surfbirdapp/surfbird/blob/master/src/renderer/components/Modal/Column.vue) can can be used as a reference for a possible integration.

## What's to be done

* Creating a Profile-modal component
* Letting the modal create a profile with the required parameters, dispatching the proper action to the state

**Comment by thepriefy** [comment]
![2017-12-01 23_46_17-profile creation dialogue issue 55 surfbirdapp_surfbird](https://user-images.githubusercontent.com/10849586/33493213-e66a4472-d6f1-11e7-80d8-ebc798f5701e.jpg)

I'm trying to create a profile creation dialogue.

When I run 'npm run dev', this window popped-up. What should I do next to test my code?

I'm also created the 'Profile.vue'. Is this corrected?

![2017-12-01 23_48_50-surfbird - c__users_thepriefy_webstormprojects_surfbird - _src_renderer_com](https://user-images.githubusercontent.com/10849586/33493341-537e1912-d6f2-11e7-8723-adefac2c7f7a.jpg)
![2017-12-01 23_49_13-surfbird - c__users_thepriefy_webstormprojects_surfbird - _src_renderer_com](https://user-images.githubusercontent.com/10849586/33493342-53b920ca-d6f2-11e7-98b4-3cc272709b90.jpg)

**Comment by pixeldesu** [comment]
@thepriefy Nice work, that looks like a correct implementation to me!

If the filebrowser opens instead of the client, it looks like there might be an issue with the JS somewhere, is the console printing out an error before the window opens? You might want to check that out!

**Comment by thepriefy** [comment]
I just found this site: https://simulatedgreg.gitbooks.io/electron-vue/content/en/

And it said that 
_"Installed vue-devtools and devtron tools for development"_

Should I install 'vue-devtools' and 'devtron' before I develop the project?

ps. by the way, can I submit the file I just shown above as a PR?

**Comment by pixeldesu** [comment]
@thepriefy No, it means these tools are both installed with the application and should show up in the inspector window (as far as I know there sometimes are race conditions that cause it not to show up, but that's a rather complicated issue)

Thank you for the PR, I'll review it now and leave some feedback on it!
