### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by pixeldesu** [surfbirdapp/surfbird#61]
### Description

To help keeping the coding style clean before even running `npm run dev` and getting warnings from ESLint, we should probably introduce an [editorconfig](http://editorconfig.org/) file that gets used by IDEs to adjust to the proper settings. It's best to find a config that correlates best to the [Standard](https://standardjs.com/) style!

**Comment by lazyd3v** [comment]
Please check https://github.com/surfbirdapp/surfbird/pull/62

**Comment by pixeldesu** [comment]
Resolved with #62
