### ISSUE TITLE
Implement the date of posts

### ISSUE THREAD

**Issue by Fubinator** [surfbirdapp/surfbird#70]
### Description

At the moment every post is showing `now`, because it's hardcoded in the html. The Twitter-API is providing a date for every post. We could pass the date from the Post component to the Post-Header component and use a computed property to get it into the right format (maybe using moment.js?). I guess we should discuss how to properly get such a date object in the "... time ago"-format. Another question is if this is trivial regarding different authentication services, so it does not break when implementing another client.

**Comment by pixeldesu** [comment]
@Fubinator I think one relatively easy way would be using [vue-timeago](https://github.com/egoist/vue-timeago), usage of that library seems straight-forward.

**Comment by pixeldesu** [comment]
Added with #73
